apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ingress-nginx
  name: xreg-server
  labels:
    run: xreg-server
spec:
  replicas: 1
  selector: 
    matchLabels:
      run: xreg-server
  template:
    metadata:
      labels:
        run: xreg-server
    spec:
      containers:
      - image: common.repositories.cloud.sap/apeirora-ows3/xreg-server:1.5.0
        imagePullPolicy: IfNotPresent
        name: xreg-server
        command: [ "/server" ]
        args: [ "--recreate" ]
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBHOST
          value: mysql
        - name: DBPORT
          value: "3306"

---

apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx
  name: xreg-server
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: xreg-server

