apiVersion: v1
kind: Config
current-context: garden-ows3--ytdzgvnl69-external
contexts:
  - name: garden-ows3--ytdzgvnl69-external
    context:
      cluster: garden-ows3--ytdzgvnl69-external
      user: garden-ows3--ytdzgvnl69
      namespace: default
  - name: garden-ows3--ytdzgvnl69-internal
    context:
      cluster: garden-ows3--ytdzgvnl69-internal
      user: garden-ows3--ytdzgvnl69
      namespace: default
clusters:
  - name: garden-ows3--ytdzgvnl69-external
    cluster:
      server: https://api.ytdzgvnl69.ows3.shoot.canary.k8s-hana.ondemand.com
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRTndjNUFHSTFIZStJTmthY1RSYm5QVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TkRBMU1qTXdPRFEyTURkYUZ3MHpOREExTWpNd09EUTJNRGRhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUE1R2tQCkF5Y0hTNStVaE9tTG9xdkRQOEZwSjZIUXFqbUo0QmV2TDdvV01XNEdNNnIzNHRjazhkR0pBMnhMUVplWkVGbWMKREhMV0xFT08xZDh5bEV6WVZvMmtROTlsbklyRkREcDFka21qblgrekkrUWRRTDVkalJBSllFSytFK1lRbTU1cAo5bVhsUFVTVTZramtqSkpVakhhK2VGakwvZjZhMU1DNEdLZEhnendDMWJZM3JIeHFqRGlOQ08vVzhpMExrbUNjCktnM0lrRStRaXk4OGdMaTRwVkVjUElZa1hGanJoUTkxWWUxWGVDTkk3L3U3dktvbWNWUjlxN3A2T2QwN3ZBWGIKS1U4UDNKUG00bVVwMExWd3J6TzYySWlQVkhkbXhYYURHMTZPTklET2tJQXFZTkRxYjdYSW5UK2pMQjRtSXJlZwo5bTIrYzE3ZU9XNkpKeXhyUjZOa1JOZEE2R0lDNlJxYnFsckEySmVFOEFvTVVTNVVwV0pzcElEa210L08yWjJaClk3cTVyeFFlckJDQVJtbklkMFk1YVVEQ3RjdFFnWHVCbXJpZFltRzQwb25QRGJ6ZzcxdFlSWUlhV0N1Z1lGY1EKdmtETWV4cXRTNGZVOXM3L3JsQURVUHVQaTV3SEJQaXpPVzU0Y1pjQlYzRXZndUpnckZyRDNVaHMrN2N0QWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUVRZdXVQdVpVRWNqcU52TnNkcTJYaDN0Q1ovakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBR0w4eFppb0UKL3M0bkN3V0hLYW9MT0xobGtDMHhNYlJ3UWw5Sk00ZnNIVXJDbWhKQ0RXKzhmdmtCaWJaYzAxUWMvQjQxOTZNbApiOC9EWVJlNDU0OEZQdTdpU1hIdTUvWUJSS3hBaDMvdE5BZW14S2NwYk8xdC8wSjYyK093dkRISlU4UW42NzFRCmwwczZMQ1BVa3RBdzJCVHVIcjUySU5VZWFrOEVZc0lYeXJicXNpR0lVTGRJeWVRK0hleUVhRHcyU0VCNTVidlEKVDVwZHNSVVQzTm1idjZwakY2YWloUU55dFZVYWRzRTZhbFpYWU9Ya3dmNVE5OEFhaTZEeDJnM0JsKzBlcCs1YgplQm9ESzdYSEVXZUdqN0pnQitjeWlFUU51Zm4rc3lVZG1iL1VZZjJXMzVsVW9RcjF1aFJHeWtodTBjVGtyVUoyClp2Mmhzd0pFNGhpeXVPQjBSYXQ3alNKcThYQ0huRVNrWUsvQ1BCRlBiSGhzekRoWUFKVGRNSERGTWlENVBGL2UKVGdhZTVJSXgxOVVlekVjVU5BWVlvMHF0REJLZXMxQlJqMnV0K0Mzc2tLY3V6RFVuY2hvaFNYbWJkbENyQTZaUQpiZ3RIL0x4MDYzMWpmNmdrUEc1bHJIQVJBcWdXdXFDRmVBWkM1RFhMai84R2JxSFluN1NoVnQ2VQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      timeoutSeconds: 600
      extensions: &ref_0
        - name: client.authentication.k8s.io/exec
          extension:
            shootRef:
              namespace: garden-ows3
              name: ytdzgvnl69
            gardenClusterIdentity: sap-landscape-canary
  - name: garden-ows3--ytdzgvnl69-internal
    cluster:
      server: https://api.ytdzgvnl69.ows3.internal.canary.k8s.ondemand.com
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRTndjNUFHSTFIZStJTmthY1RSYm5QVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TkRBMU1qTXdPRFEyTURkYUZ3MHpOREExTWpNd09EUTJNRGRhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUE1R2tQCkF5Y0hTNStVaE9tTG9xdkRQOEZwSjZIUXFqbUo0QmV2TDdvV01XNEdNNnIzNHRjazhkR0pBMnhMUVplWkVGbWMKREhMV0xFT08xZDh5bEV6WVZvMmtROTlsbklyRkREcDFka21qblgrekkrUWRRTDVkalJBSllFSytFK1lRbTU1cAo5bVhsUFVTVTZramtqSkpVakhhK2VGakwvZjZhMU1DNEdLZEhnendDMWJZM3JIeHFqRGlOQ08vVzhpMExrbUNjCktnM0lrRStRaXk4OGdMaTRwVkVjUElZa1hGanJoUTkxWWUxWGVDTkk3L3U3dktvbWNWUjlxN3A2T2QwN3ZBWGIKS1U4UDNKUG00bVVwMExWd3J6TzYySWlQVkhkbXhYYURHMTZPTklET2tJQXFZTkRxYjdYSW5UK2pMQjRtSXJlZwo5bTIrYzE3ZU9XNkpKeXhyUjZOa1JOZEE2R0lDNlJxYnFsckEySmVFOEFvTVVTNVVwV0pzcElEa210L08yWjJaClk3cTVyeFFlckJDQVJtbklkMFk1YVVEQ3RjdFFnWHVCbXJpZFltRzQwb25QRGJ6ZzcxdFlSWUlhV0N1Z1lGY1EKdmtETWV4cXRTNGZVOXM3L3JsQURVUHVQaTV3SEJQaXpPVzU0Y1pjQlYzRXZndUpnckZyRDNVaHMrN2N0QWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUVRZdXVQdVpVRWNqcU52TnNkcTJYaDN0Q1ovakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBR0w4eFppb0UKL3M0bkN3V0hLYW9MT0xobGtDMHhNYlJ3UWw5Sk00ZnNIVXJDbWhKQ0RXKzhmdmtCaWJaYzAxUWMvQjQxOTZNbApiOC9EWVJlNDU0OEZQdTdpU1hIdTUvWUJSS3hBaDMvdE5BZW14S2NwYk8xdC8wSjYyK093dkRISlU4UW42NzFRCmwwczZMQ1BVa3RBdzJCVHVIcjUySU5VZWFrOEVZc0lYeXJicXNpR0lVTGRJeWVRK0hleUVhRHcyU0VCNTVidlEKVDVwZHNSVVQzTm1idjZwakY2YWloUU55dFZVYWRzRTZhbFpYWU9Ya3dmNVE5OEFhaTZEeDJnM0JsKzBlcCs1YgplQm9ESzdYSEVXZUdqN0pnQitjeWlFUU51Zm4rc3lVZG1iL1VZZjJXMzVsVW9RcjF1aFJHeWtodTBjVGtyVUoyClp2Mmhzd0pFNGhpeXVPQjBSYXQ3alNKcThYQ0huRVNrWUsvQ1BCRlBiSGhzekRoWUFKVGRNSERGTWlENVBGL2UKVGdhZTVJSXgxOVVlekVjVU5BWVlvMHF0REJLZXMxQlJqMnV0K0Mzc2tLY3V6RFVuY2hvaFNYbWJkbENyQTZaUQpiZ3RIL0x4MDYzMWpmNmdrUEc1bHJIQVJBcWdXdXFDRmVBWkM1RFhMai84R2JxSFluN1NoVnQ2VQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      extensions: *ref_0
users:
  - name: garden-ows3--ytdzgvnl69
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: kubectl-gardenlogin
        args:
          - get-client-certificate
        provideClusterInfo: true
        interactiveMode: IfAvailable
        installHint: >-
          Follow the instructions on

          - https://github.com/gardener/gardenlogin#installation to install and

          - https://github.com/gardener/gardenlogin#configure-gardenlogin to
          configure the gardenlogin credential plugin.


          The following is a sample configuration for gardenlogin as well as
          gardenctl. Place the file under ~/.garden/gardenctl-v2.yaml.


          ---

          gardens:
            - identity: sap-landscape-canary
              kubeconfig: "<path-to-garden-cluster-kubeconfig>"
          ...


          Alternatively, you can run the following gardenctl command:


          $ gardenctl config set-garden sap-landscape-canary --kubeconfig
          "<path-to-garden-cluster-kubeconfig>"


          Note that the kubeconfig refers to the path of the garden cluster
          kubeconfig which you can download from the Account page.
